# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: TideDesk.TideDesk
PackageVersion: 0.1.0-alpha.13
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: tidedesk.exe
  PortableCommandAlias: tidedesk
ReleaseDate: 2026-10-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/cristiangirlea/tidedesk/releases/download/v0.1.0-alpha.13/tidedesk-0.1.0-alpha.13-windows-x64.zip
  InstallerSha256: 8782460C53BC3C644A53DB5C1B7C9CE57758E43843CF0B12ECFE677AFBDDB696
ManifestType: installer
ManifestVersion: 1.12.0
